app_l3/urls.py
from django.urls import path
from .views import user_views,ticket_views,classification_views

urlpatterns = [
    
    path("",user_views.login_user,name="login_form"),
    path("logout/",user_views.logout_user,name="logout_user"),
    path("register/",user_views.register_user,name="register_user_form"), 
    path("user/<int:user_id>",user_views.display_user,name="display_user"), 
    path("user/update/<int:user_id>/",user_views.update_user,name="update_user_form"), 
    path("user/delete/<int:user_id>/",user_views.delete_user,name="delete_user"), 

    path("home/<str:type_user>/",ticket_views.home,name="home"),
    
    path("ticket/create/",ticket_views.add_ticket,name="add_ticket_form"),
    path("ticket/display/<int:ticket_id>/",ticket_views.console_ticket,name="console_ticket"),
    path("ticket/update/<int:ticket_id>/",ticket_views.update_ticket,name="update_ticket_form"),
    path("ticket/delete/<int:ticket_id>/",ticket_views.delete_ticket,name="delete_ticket"),
    
    path("ticket/solution/<int:ticket_id>",ticket_views.add_solution,name="add_solution_form"),
    path("ticket/confirm/<int:ticket_id>/<int:solution_id>/",ticket_views.confirm_ticket,name="confirm_ticket"),
    
    path("ticket/solution/download-<str:ticket_title>-<int:solution_id>/",ticket_views.download_solution,name="download_solution"),
    path('download-attachment/<int:ticket_id>/', ticket_views.download_attachment, name='download_attachment'),
    path("export/<str:filename>",ticket_views.export_to_csv_by_me,name="export_to_csv_by_me"),
    path("export/<str:filename>",ticket_views.export_to_csv_all,name="export_to_csv_all"),
    path("category/create/",classification_views.add_category,name="add_category_form"),
    path("priority/create/",classification_views.add_priority,name="add_priority_form"),
    path("status/create",classification_views.add_status,name="add_status_form"),
    
    path('ticket/conversation/<int:ticket_id>',ticket_views.ticket_conversation,name='ticket_conversation')
]

incident_managment_L3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app_l3.urls")),   
]

app_l3/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class UserModel(AbstractUser):

    username = models.CharField(max_length = 150,unique=True,blank=False,null=False)
    first_name = models.CharField(max_length = 100,blank=False,null=False)
    last_name = models.CharField(max_length = 150,blank=False,null=False)
    email = models.EmailField(blank=False,null=False)
    password = models.CharField(max_length = 100,blank=False,null=False)
    number = models.IntegerField(blank=False,null=False)

    is_observer = models.BooleanField(null=True,default=False)
    is_self_service = models.BooleanField(null=True,default=False)
    is_technician = models.BooleanField(null=True,default=False)

    is_active = models.BooleanField(null=True,default=True)
    is_superuser =  models.BooleanField(null=True,default=False)
    
    REQUIRED_FIELDS = ['first_name','last_name','email','password','number']
    USERNAME_FIELD = 'username'
    
    class Meta:
        db_table = 'user_table'
        
    def __str__(self):
        return self.username

class AdminModel(models.Model):
    username = models.CharField(max_length = 150,unique=True)
    admin_as_user = models.OneToOneField(UserModel,on_delete=models.PROTECT,primary_key=True)
    creation_date = models.DateField(null=True,blank=True) 
    
    class Meta:
        db_table = 'admin_table'

class TechnicianModel(models.Model):
    username = models.CharField(max_length = 150,unique=True)
    tech_as_user = models.OneToOneField(UserModel,on_delete=models.PROTECT,primary_key=True)
    creation_date = models.DateField(null=True,blank=True) 
    
    class Meta:
        db_table = 'technician_table'
        
    def __str__(self):
        if self.tech_as_user.first_name and self.tech_as_user.last_name:
            return f"{self.tech_as_user.first_name} {self.tech_as_user.last_name}"
        elif self.tech_as_user.first_name:
            return self.tech_as_user.first_name
        elif self.tech_as_user.last_name:
            return self.tech_as_user.last_name
        else:
            return self.username

class ObserverModel(models.Model):
    username = models.CharField(max_length = 150,unique=True)
    observer_as_user = models.OneToOneField(UserModel,on_delete=models.PROTECT,primary_key=True)
    creation_date = models.DateField(null=True,blank=True) 
    
    class Meta:
        db_table = 'observer_table'

class SelfServiceModel(models.Model):
    username = models.CharField(max_length = 150,unique=True)
    self_service_as_user = models.OneToOneField(UserModel,on_delete=models.PROTECT,primary_key=True)
    creation_date = models.DateField(null=True,blank=True) 
    
    class Meta:
        db_table = 'self_service_table'        

class CategoryModel(models.Model):
    
    CATEGORY_CHOICES = (
        ('hardware', 'Hardware'),
        ('software', 'Software'),
        ('network', 'Network'),
        ('printer', 'Printer'),
        ('phone', 'Phone'),
        ('laptop', 'Laptop'),
    )
    
    category_name = models.CharField(max_length = 150,unique=True,primary_key=True,choices=CATEGORY_CHOICES)
    description = models.TextField()
    category_creation_date = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    
    def __str__(self) -> str:
        return self.category_name
    
    class Meta:
        db_table = 'category_table'

class PriorityModel(models.Model):
    
    PRIORITY_CHOICES = (
        ('veryhigh', 'Very High'),
        ('high', 'High'),
        ('medium', 'Medium'),
        ('low', 'Low'),
    )
    
    priority_name = models.CharField(max_length = 150,unique=True,primary_key=True,choices=PRIORITY_CHOICES)
    description = models.TextField()
    priority_creation_date = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    
    def __str__(self) -> str:
        return self.priority_name
    
    class Meta:
        db_table = 'priority_table'

class StatusModel(models.Model):
    
    STATUS_CHOICES = (
        #('new', 'New'),
        ('pending', 'Pending'),
        ('ongoing', 'Ongoing'),
        ('solved', 'Solved'),
        ('closed', 'Closed'),
    )
    
    status_name = models.CharField(max_length = 150,unique=True,primary_key=True,choices=STATUS_CHOICES)
    description = models.TextField()
    status_creation_date = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    
    def __str__(self) -> str:
        return self.status_name
    
    class Meta:
        db_table = 'status_table'

class TicketsModel(models.Model):
    
    title = models.CharField(max_length = 150,unique=True,blank=False, null=False)
    category = models.ForeignKey(CategoryModel,on_delete=models.CASCADE,blank=False, null=False)
    priority = models.ForeignKey(PriorityModel,on_delete=models.CASCADE,blank=False, null=False)
    status = models.ForeignKey(StatusModel,on_delete=models.CASCADE,blank=False,null=False)
    assigned_by = models.ForeignKey(UserModel,on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(TechnicianModel,on_delete=models.CASCADE,blank=True,null=True)
    description = models.TextField(blank=False,null=False)
    attachment = models.FileField(blank=True,null=True,upload_to='app_l3/ticket_attachments/')
    ticket_creation_date = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    
    class Meta:
        db_table = 'tickets_table'
        
    def __str__(self) -> str:
        return self.title

class TicketSolutionModel(models.Model):
    
    targeted_ticket = models.ForeignKey(TicketsModel,on_delete=models.CASCADE,blank=False,null=False)
    solution_by = models.ForeignKey(TechnicianModel,on_delete=models.PROTECT)
    solution_description = models.TextField(blank=False,null=False)
    ticket_solution_date = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    confirmed_solution = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'tickets_solutions_table'

class TicketSolutionAttachmentModel(models.Model):
    
    targeted_solution = models.ForeignKey(TicketSolutionModel,on_delete=models.PROTECT,blank=False,null=False)
    attachment = models.FileField(blank=True,null=True,upload_to='downloaded_solutions/')
    
    class Meta:
        db_table = 'tickets_solutions_attachment_table'

class ConversationModel(models.Model):
    ticket = models.ForeignKey(TicketsModel, on_delete=models.CASCADE, blank=False, null=False)
    sender = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='sent_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['timestamp']  # Ensure conversations are ordered by timestamp

app_l3/views/classification_views.py
from django.shortcuts import render
from django.shortcuts import render,redirect
from app_l3.forms import AddCategoryForm,AddPriorityForm,AddStatusForm

def add_category(response):
    type_user = response.session.get('type_user')
    if response.method == "POST":
        
        AddCategory = AddCategoryForm(response.POST)
        if AddCategory.is_valid():
            AddCategory.save()
            return redirect('home',type_user=response.session.get('type_user'))
        else:
            print("Category Form is invalid")
            return render(response, 'template/app_l3/ticket.html',context)
    else:
        AddCategory = AddCategoryForm()
        
    context={'add_category_form':AddCategory,'type_user':type_user}
    return render(response,'templates/tickets_details/category.html',context)

def add_priority(response):
    type_user = response.session.get('type_user')
    if response.method == "POST":
        
        AddPriority = AddPriorityForm(response.POST)
        if AddPriority.is_valid():
            AddPriority.save()
            return redirect('home',type_user=response.session.get('type_user'))
        else:
            print("Priority Form is invalid")
            return render(response, 'template/app_l3/ticket.html', context)
    else:
        AddPriority = AddPriorityForm()
        
    context= {'add_priority_form':AddPriority,'type_user':type_user}
    return render(response,'templates/tickets_details/priority.html',context )

def add_status(response):
    type_user = response.session.get('type_user')
    if response.method == "POST":
        
        AddStatus = AddStatusForm(response.POST)
        if AddStatus.is_valid():
            AddStatus.save()
            return redirect('add_ticket_form')
        else:
            print("Status Form is invalid")
            return render(response, 'template/app_l3/ticket.html', context)
    else:
        AddStatus = AddStatusForm()
    
    context={'add_status_form':AddStatus,'type_user':type_user}
    return render(response,'templates/tickets_details/status.html', context)

app_l3/views/user_views.py
from django.contrib.auth.password_validation import password_validators_help_texts
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.hashers import make_password
from app_l3.forms import RegisterUserForm
from django.contrib import messages
from app_l3.models import *

def login_user(response):
    if response.user.is_authenticated:
        return redirect("home",type_user=response.session.get('type_user'))
    
    if response.method == "POST":
        username = response.POST["username"]
        password = response.POST["password"]
        USER = authenticate(response,username=username,password=password)
        if USER is not None:
            user = UserModel.objects.get(username=username)
            if user.is_staff:
                login(response,user=USER)
                return redirect("home",type_user='staff')
            if user.is_technician:
                login(response,user=USER)
                return redirect("home",type_user='technician')
            if user.is_self_service:
                login(response,user=USER)
                return redirect("home",type_user='self_service')
            if user.is_observer:
                login(response,user=USER)
                return redirect("home",type_user='observer')
        else:
            messages.success(response,("there was Authentication error"))
            return redirect("login_form")
    else:
        return render(response, "templates/login_user.html", {})

def logout_user(response):
    logout(response)
    messages.success(response,("You Did Logout"))
    return redirect("login_form")

def register_user(response):
    type_user = response.session.get('type_user')
    
    if response.method == "POST":
        CreationForm = RegisterUserForm(response.POST)
        if CreationForm.is_valid():
            username = CreationForm.cleaned_data["username"]
            password = CreationForm.cleaned_data["password"]
            hash_pass = make_password(password=password)
            CreationForm.instance.password = hash_pass
            CreationForm.instance.is_active = True
            CreationForm.save()
            model = UserModel.objects.get(username=username)
            if CreationForm.instance.is_staff:
                AdminModel.objects.create(username=username, admin_as_user=model)
            if CreationForm.instance.is_observer:
                ObserverModel.objects.create(username=username, observer_as_user=model)
            if CreationForm.instance.is_self_service:
                SelfServiceModel.objects.create(username=username, self_service_as_user=model)
            if CreationForm.instance.is_technician:
                TechnicianModel.objects.create(username=username, tech_as_user=model)
            messages.success(response,("User Registered"))
            redirect('register_user_form')
            
        else:
            messages.success(response,("Unvalid Register Form"))
            for txt in password_validators_help_texts():
                messages.success(response,txt)
            redirect('register_user_form')
            
    else:
        CreationForm = RegisterUserForm()
        
    context={'register_user_form': CreationForm, 'type_user': type_user}
    return render(response, "templates/register_user.html",context)

def update_user(response,user_id):
    type_user = response.session.get('type_user')
    
    target_user = UserModel.objects.get(pk=user_id)
    activated = target_user.is_active
    updated_user_form = RegisterUserForm(response.POST or None, instance=target_user)
    
    if response.method == "POST":
        if updated_user_form.is_valid():
            
            if updated_user_form.instance.is_staff:
                if AdminModel.objects.get(pk=user_id):
                    pass
                else:
                    AdminModel.objects.create(pk=user_id, admin_as_user=target_user)
            if updated_user_form.instance.is_observer:
                if ObserverModel.objects.get(pk=user_id):
                    pass
                else:
                    ObserverModel.objects.create(pk=user_id, observer_as_user=target_user)
                
            if updated_user_form.instance.is_self_service:
                if SelfServiceModel.objects.get(pk=user_id):
                    pass
                else:
                    SelfServiceModel.objects.create(pk=user_id, self_service_as_user=target_user)
                    
            if updated_user_form.instance.is_technician:
                if TechnicianModel.objects.get(pk=user_id) :
                    pass
                else:
                    TechnicianModel.objects.create(pk=user_id, tech_as_user=target_user)
            updated_user_form.save()
            
            return redirect('display_user', user_id=target_user.id)
        
        print(updated_user_form.errors)
    context = {'updated_user_form':updated_user_form,'activated':activated,'type_user':type_user}
    return render(response, "templates/users/user_update.html",context)

def display_user(response,user_id):
    type_user = response.session.get('type_user')
    user = get_object_or_404(UserModel, pk=user_id)

    context = {'type_user': type_user,'user': user}
    return render(response, "templates/users/user_display.html", context)

def delete_user(response,user_id):
    if response.method == "POST":
        try:
            user_deletion = UserModel.objects.get(pk=user_id)
            user_deletion.is_active = False
            user_deletion.save()
            return redirect('home',type_user=response.session.get('type_user'))
        except UserModel.DoesNotExist:
            return HttpResponse("Object not found", status=404)
    else:
        # Handle GET requests or other methods
        return HttpResponse("Method not allowed", status=401)

app_l3/templates/users/user_display.html
{% extends 'base.html' %}

{% load static %}

{% block css%}
<link href="{% static 'app_l3/style/users/user_display.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block title %}Display{% endblock %}

{% block content %}

<body>
    <div class="mainscreen">
        <div class="card">
            <div class="leftside"></div>
            <div class="rightside">
                <h1>User Details</h1>
                        <h2>(+)Firstname / Lastname </h2>
                        <p>{{ user.first_name }} / {{ user.last_name }}</p>

                        <h2>(+) ID / Username</h2>
                        <p>{{ user.id }} / {{ user.username }}</p>

                        <h2>(+)Number / Email</h2>
                        <p>{{ user.number }} / {{ user.email }}</p>

                        <h2>(+)Class : {% if user.is_staff %} STAFF {%endif%}
                            {% if user.is_observer %} OBSERVER {%endif%}
                            {% if user.is_self_service %}SELF SERVICE{%endif%}
                            {% if user.is_technician %}TECHNICIAN{%endif%}
                        </h2>
                        <h2>(+)Activition : {% if user.is_active %}Active{%else%}Not Active{%endif%}</h2>

                <div class="set">
                    <button id="returnBtn" type="submit">Return</button>
                    <a href="{% url 'update_user_form' user_id=user.id %}" style="font-size: 13px;" ><button type="submit">Update User</button></a>

                    <form method="post" action="{% url 'delete_user' user_id=user.id %}">
                        {% csrf_token %}
                        <button type="submit" id="delete_btn" style="font-size: 13px" onclick="return confirm('Are you sure you want to delete this User? Note: it will only deactivate his account not fully delete from the database')">Delete User</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

{% endblock %}

app_l3/templates/users/user_update.html
{% extends 'base.html' %}

{% load static %}

{% block css%}
<link href="{% static 'app_l3/style/users/register_style.css' %}" type="text/css" rel="stylesheet" />
<link href="{% static 'app_l3/style/users/user_perms.css' %}" type="text/css" rel="stylesheet" />
{% endblock %}

{% block title %}Update{% endblock %}

{% block content %}
<body>

<section>  <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>
<div class="signin"> 
    <div class="content"> 
      <h2>Update User</h2> 

      <div class="form" > 
        <form class="form" action="" method="post" >
            {% csrf_token %}
          <div class="inputBox">
            {{updated_user_form.first_name}}<i>First Name</i>
          </div>
          <div class="inputBox">
            {{updated_user_form.last_name}}<i>Last Name</i>
          </div>
  
          <div class="inputBox"> 
            {{updated_user_form.username}}<i>Username</i> 
          </div>
  
          <div class="inputBox"> 
            {{updated_user_form.number}}<i>Number</i> 
          </div>
  
          <div class="inputBox"> 
            {{updated_user_form.email}}<i>Email</i> 
          </div>	 
  
          <div class="inputBox"> 
            {{updated_user_form.password}}<i>Password</i> 
          </div> 
  
          <div class="big_wrapper">
            <div class="wrapper">
              {{updated_user_form.is_staff}}
              <label for="id_is_staff">Staff</label>
              {{updated_user_form.is_technician}}
              <label for="id_is_technician">is_technician</label>
              {{updated_user_form.is_self_service}}
              <label for="id_is_self_service">is_self_service</label>
              {{updated_user_form.is_observer}}
              <label for="id_is_observer">observer</label>
            </div>
          </div>

          {% if not activated %}
          <div class="big_wrapper">
            <div class="wrapper">
              {{updated_user_form.is_active}}
              <label for="id_is_active">Activate User</label>
            </div>
          </div>
          {% endif %}
  
          <div class="set">
            <button id="returnBtn" type="submit">Return</button>
            <button type="submit">Register</button>
          </div>
        </form>
    </div> 
  
    </div> 
</div> 
</section> <!-- partial --> 
</body>
{% endblock %}